# Header
menu:
  主页: /
  归档: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  #主题作者: http://arvinxiang.com
  #热前端: http://reqianduan.com
  #远程.work: http://yuancheng.work
  我的github: https://github.com/mooncaker816
  我的coding: https://coding.net/u/mooncaker816

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
#duoshuo_shortname: reqianduan

# Baidu share
baidushare: true

# pinglun
pinglun: true
pinglun_owner: mooncaker816
pinglun_repo: mooncaker816.github.io
pinglun_client_id: 60b359cdeb3c484dbaa1
pinglun_client_secret: 7df3c9ab596e17a67e10b61a38c4f1c7ca976b63